# Generated by Django 6.0.1 on 2026-03-01 11:15

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='akount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='ism')),
                ('last_name', models.CharField(max_length=25, verbose_name='familya')),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('malumot', models.CharField(blank=True, max_length=100, null=True, verbose_name='umumiy malumot')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ism')),
                ('last_name', models.CharField(max_length=190, verbose_name='familya')),
                ('age', models.IntegerField(verbose_name='yosh')),
                ('position', models.CharField(max_length=99, verbose_name='lavozim')),
                ('haqida', models.TextField(max_length=199, verbose_name='malumot')),
                ('image', models.ImageField(upload_to='', verbose_name='rasm uchun joy')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.akount', verbose_name='kmni ishchilari')),
            ],
            options={
                'verbose_name': 'hodim',
                'verbose_name_plural': 'hodimlar',
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ega', models.IntegerField(verbose_name='baho')),
                ('comment', models.TextField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='tasdiqlash')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee', verbose_name='hodimlar roxati')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='ish haqi')),
                ('bonus', models.CharField(max_length=100)),
                ('id_active', models.BooleanField(default=True, verbose_name='berilgan berilmaganligi')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.employee', verbose_name='hodim')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_entries', to='management.akount', verbose_name='ishchi')),
            ],
            options={
                'verbose_name': 'oylik',
                'verbose_name_plural': 'oyliklar',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='kelgan kelmaganligi haqida')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='izoh')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.akount', verbose_name='ishchi')),
                ('money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.monthly', verbose_name='ish haqi')),
            ],
            options={
                'verbose_name': 'davomat',
                'verbose_name_plural': 'davomatlar',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_name', models.CharField(max_length=100, verbose_name='lavozim turi')),
                ('www', ckeditor.fields.RichTextField(verbose_name='ish haqida')),
                ('is_active', models.BooleanField(default=True, verbose_name='hozir bormi bunday lavozim')),
                ('ega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.akount', verbose_name='boshliq')),
            ],
            options={
                'verbose_name': 'lavozim',
                'verbose_name_plural': 'lavozimlar',
            },
        ),
        migrations.AddField(
            model_name='monthly',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.position', verbose_name='lavozim'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25, verbose_name='telefon raqam')),
                ('lacation', models.CharField(max_length=100, verbose_name='lakatsiya')),
                ('image', models.ImageField(max_length=255, upload_to='profiles/', verbose_name='rasm uchun joy')),
                ('birth_day', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.akount', verbose_name='akkount')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.profile'),
        ),
    ]
