# Generated by Django 6.0.1 on 2026-03-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=100, verbose_name='vazifa')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee', verbose_name='ism')),
            ],
            options={
                'verbose_name': 'vazifa',
                'verbose_name_plural': 'vazifalar',
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.TextField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.employee', verbose_name='ism')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.tasks', verbose_name='vazifani bajarish shartlari')),
            ],
            options={
                'verbose_name': 'proyekt',
                'verbose_name_plural': 'proyektlar',
            },
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100, verbose_name='sababi')),
                ('money', models.IntegerField(verbose_name='summa')),
                ('name', models.ManyToManyField(to='management.employee', verbose_name='ism')),
            ],
        ),
    ]
