# Generated by Django 6.0.1 on 2026-03-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_tasks_projects_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='warnings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='tasdiq'),
        ),
    ]
