# Generated by Django 6.0.1 on 2026-02-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat nomi')),
                ('discription', models.TextField(verbose_name='tavsif')),
                ('activity', models.BooleanField(default=True, verbose_name='faolligi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefon nomer')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'nonushta',
                'verbose_name_plural': 'nonushtalar',
            },
        ),
        migrations.CreateModel(
            name='Delivery_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='ism')),
                ('last_name', models.CharField(max_length=20, verbose_name='familya')),
                ('car', models.CharField(max_length=20, verbose_name='moshina turi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefon nomer')),
                ('passport', models.CharField(max_length=20, verbose_name='pasport raqam')),
            ],
            options={
                'verbose_name': 'dastafchik',
                'verbose_name_plural': 'dastafchiklar',
            },
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('discription', models.CharField(max_length=100, verbose_name='tavsif')),
                ('locetion', models.CharField(max_length=25, verbose_name='joylashuv')),
                ('price', models.IntegerField(verbose_name='narxi')),
                ('bonus', models.CharField(max_length=25, verbose_name='sovga')),
            ],
            options={
                'verbose_name': 'kechki ovat',
                'verbose_name_plural': 'kechki ovqatlar',
            },
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat nomi')),
                ('discription', models.TextField(verbose_name='tavsif')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefon nomer')),
                ('email', models.EmailField(max_length=254)),
                ('locetion', models.CharField(max_length=25, verbose_name='manzil')),
            ],
            options={
                'verbose_name': 'tushlik',
                'verbose_name_plural': 'tushliklar',
            },
        ),
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ism')),
                ('price', models.IntegerField()),
                ('phone_number', models.CharField(max_length=25, verbose_name='telefon nomer')),
                ('zakaz', models.BooleanField(verbose_name='yetb borganligi haqida')),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.breakfast', verbose_name='nonushta')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.delivery_driver', verbose_name='yetqazib beruvchi')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.dinner', verbose_name='kechki ovqat')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.lunch', verbose_name='tushlik')),
            ],
            options={
                'verbose_name': 'dastafka',
                'verbose_name_plural': 'dastafkalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oshpaz', models.CharField(max_length=100, verbose_name='kim qilganligi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='telefon nomer')),
                ('locetion', models.CharField(max_length=25, verbose_name='joylashuv')),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.breakfast', verbose_name='nonushta')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.dinner', verbose_name='kechki ovqat')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaran.lunch', verbose_name='tushlik')),
            ],
            options={
                'verbose_name': 'maxsulot',
                'verbose_name_plural': 'maxsulotlar',
            },
        ),
    ]
