# Generated by Django 6.0.1 on 2026-02-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': 'nonushta',
                'verbose_name_plural': 'nonushtalar',
            },
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': 'kechki ovat',
                'verbose_name_plural': 'kechki ovqatlar',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100, verbose_name='tavsif')),
            ],
            options={
                'verbose_name': 'tushlik',
                'verbose_name_plural': 'tushliklar',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.breakfast', verbose_name='nomi')),
                ('dinner_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.dinner', verbose_name='nomi')),
                ('food_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.food', verbose_name='nomi')),
                ('lunch_id', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.lunch', verbose_name='nomi')),
            ],
        ),
    ]
