# Generated by Django 6.0.1 on 2026-02-07 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.breakfast', verbose_name='nonushta'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dinner_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.dinner', verbose_name='kechki ovqat'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.food', verbose_name='food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch_id',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kafe.lunch', verbose_name='tushlik'),
        ),
    ]
