# Generated by Django 6.0.1 on 2026-03-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentit', '0002_alter_category_options_remove_item_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': "Ko'p beriladigan savol", 'verbose_name_plural': "Ko'p beriladigan savollar"},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Ijara', 'verbose_name_plural': 'Ijaralar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Sharh', 'verbose_name_plural': 'Sharhlar'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'kelishuv', 'verbose_name_plural': 'kelishuvlar'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Tanlangan mahsulot', 'verbose_name_plural': 'Tanlangan mahsulotlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rentit.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_main',
            field=models.ImageField(upload_to='items/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Mavjudmi?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.profile', verbose_name='Esh egasi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_per_day',
            field=models.IntegerField(verbose_name='Kunlik narxi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlanganmi?'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.item', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.profile', verbose_name='Ijaraga oluvchi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_price',
            field=models.IntegerField(verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.item', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Reyting'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=100, verbose_name='Sharh qoldiruvchi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(max_length=50, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.profile', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.item', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentit.profile', verbose_name='Profil'),
        ),
    ]
