# Generated by Django 6.0.1 on 2026-03-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma elementi', 'verbose_name_plural': 'Buyurtma elementlari'},
        ),
        migrations.AlterModelOptions(
            name='orderrental',
            options={'verbose_name': 'Ijara buyurtmasi', 'verbose_name_plural': 'Ijara buyurtmalari'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tariflar'},
        ),
        migrations.AlterModelOptions(
            name='tariffcustomer',
            options={'verbose_name': 'Mijoz tarifi', 'verbose_name_plural': 'Mijozlar tariflari'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=255, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kupon kodi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(max_length=50, verbose_name="Mijoz turi (talaba/o'qituvchi)"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.book', verbose_name='Kitob'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.orderrental', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sotilgan vaqtdagi narxi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Buyurtma nomi'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='status',
            field=models.CharField(default='pending', max_length=50, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy summa'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (kun)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_name',
            field=models.CharField(max_length=100, verbose_name='Tarif nomi'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif narxi'),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.customer', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faollik holati'),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.tariff', verbose_name='Tarif'),
        ),
    ]
