# Generated by Django 6.0.1 on 2026-03-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_alter_book_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderrental',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Ombordagi qoldiq'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(max_length=50, verbose_name='Mijoz turi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ismi sharifi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderrental',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Umumiy summa'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration_days',
            field=models.IntegerField(default=30, verbose_name='Davomiyligi (soat)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_price',
            field=models.IntegerField(verbose_name='Tarif narxi'),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tariffcustomer',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.tariff'),
        ),
    ]
