# Generated by Django 6.0.1 on 2026-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ism')),
                ('money', models.CharField(max_length=100, verbose_name='pul')),
            ],
            options={
                'verbose_name': 'mijoz',
                'verbose_name_plural': 'mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='mahsulot')),
                ('discription', models.CharField(max_length=100, verbose_name='tavsif')),
            ],
        ),
    ]
