# Generated by Django 6.0.1 on 2026-02-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketing.market', verbose_name='mahsulot'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='money',
            field=models.IntegerField(),
        ),
    ]
