# Generated by Django 6.0.1 on 2026-02-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='familya')),
                ('age', models.IntegerField(verbose_name='yosh')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ozodbek.food', verbose_name='ovqat')),
            ],
            options={
                'verbose_name': 'mijoz',
                'verbose_name_plural': 'mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ozodbek.customer', verbose_name='mijoz ismi')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ozodbek.food', verbose_name='ovqat nomi')),
            ],
            options={
                'verbose_name': 'zakaz',
                'verbose_name_plural': 'zakazlar',
            },
        ),
        migrations.CreateModel(
            name='Restarant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ozodbek.food', verbose_name='ovqat zakazz')),
            ],
        ),
    ]
