# Generated by Django 6.0.1 on 2026-02-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ozodbek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='restaran nomi')),
                ('email', models.CharField(max_length=100, verbose_name='manzil')),
                ('phone_number', models.CharField(max_length=100, verbose_name='telefon nomer')),
            ],
            options={
                'verbose_name': 'Restaran',
                'verbose_name_plural': 'Restaranlar',
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'ovqat', 'verbose_name_plural': 'ovqatlar'},
        ),
        migrations.AddField(
            model_name='food',
            name='money',
            field=models.CharField(default=1, max_length=10, verbose_name='narxi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='restauraant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ozodbek.restaurant', verbose_name='restaran nomi'),
        ),
        migrations.DeleteModel(
            name='Restarant',
        ),
    ]
