# Generated by Django 6.0.1 on 2026-02-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ozodbek', '0002_restaurant_alter_food_options_food_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='restauraant',
        ),
    ]
