# Generated by Django 6.0.1 on 2026-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ozodbek', '0003_remove_food_restauraant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='ism'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1, max_length=100, verbose_name='tel nomer'),
            preserve_default=False,
        ),
    ]
