# Generated by Django 6.0.1 on 2026-02-01 11:24

import auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_malumot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeli', models.CharField(max_length=100, verbose_name=auto.models.Malumot)),
            ],
        ),
    ]
