# Generated by Django 6.0.1 on 2026-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_moshina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshina',
            name='modeli',
            field=models.CharField(max_length=100, verbose_name='Malumot'),
        ),
    ]
