# Generated by Django 6.0.1 on 2026-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_moshina_modeli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moshina',
            options={'verbose_name': 'Moshina', 'verbose_name_plural': 'Moshinalar'},
        ),
    ]
