# Generated by Django 6.0.1 on 2026-02-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_moshina_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malumot',
            options={'verbose_name': 'Malumot', 'verbose_name_plural': 'Malumotlar'},
        ),
        migrations.AlterField(
            model_name='moshina',
            name='modeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.malumot'),
        ),
    ]
