# Generated by Django 6.0.1 on 2026-02-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_malumot_options_alter_moshina_modeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='moshina',
            name='akount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto.malumot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moshina',
            name='modeli',
            field=models.CharField(max_length=100),
        ),
    ]
