# Generated by Django 6.0.1 on 2026-02-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_moshina_akount_alter_moshina_modeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moshina',
            old_name='modeli',
            new_name='moshina_modeli',
        ),
    ]
