# Generated by Django 6.0.1 on 2026-02-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_rename_modeli_moshina_moshina_modeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moshina',
            old_name='moshina_modeli',
            new_name='modeli',
        ),
    ]
