# Generated by Django 6.0.1 on 2026-02-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_rename_moshina_modeli_moshina_modeli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moshina',
            name='modeli',
        ),
    ]
