# Generated by Django 6.0.1 on 2026-02-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_remove_moshina_modeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moshina',
            name='akount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.malumot'),
        ),
    ]
