# Generated by Django 6.0.1 on 2026-02-01 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_alter_moshina_akount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moshina',
            name='akount',
        ),
        migrations.AddField(
            model_name='moshina',
            name='modeli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto.malumot'),
            preserve_default=False,
        ),
    ]
