# Generated by Django 6.0.1 on 2026-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='ball',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='yosh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staj',
            field=models.IntegerField(),
        ),
    ]
