# Generated by Django 6.0.1 on 2026-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_mark_ball_alter_student_age_alter_teacher_staj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='mark',
            name='ball',
            field=models.IntegerField(max_length=10),
        ),
    ]
