# Generated by Django 6.0.1 on 2026-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_teacher_last_name_alter_mark_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='ball',
            field=models.IntegerField(),
        ),
    ]
