# Generated by Django 6.0.1 on 2026-02-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'talaba', 'verbose_name_plural': 'talabalar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'mavzu', 'verbose_name_plural': 'mavzular'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Oqtuvchi', 'verbose_name_plural': 'oqtuvchilar'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='sana'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(verbose_name='ball'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.student', verbose_name='talaba'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.subject', verbose_name='mavzu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='yosh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ism'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ism'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaa.teacher', verbose_name='oqtuvchisi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(verbose_name='staj'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ism'),
        ),
    ]
