# Generated by Django 6.0.1 on 2026-02-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0002_alter_student_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Ball', 'verbose_name_plural': 'Ballar'},
        ),
    ]
