# Generated by Django 6.0.1 on 2026-02-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0003_alter_grade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'fan', 'verbose_name_plural': 'fanlar'},
        ),
    ]
